language: generic

# Docker requires superuser permissions
sudo: required

# Tell Travis we need a copy of Docker installed
services:
  - docker

# Any commands we need to run before we run tests or deploy our project
before_install:
  - docker build -t jaredhill4/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jaredhill4/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-902421388945"
  bucket_path: "docker-react"
  on:
    branch: master
